import type { FontPair } from '../fontPairTypes';

export const DISPLAY_SANS_PAIRS: FontPair[] = [
  {
    id: 'display-space-mono-jakarta',
    displayName: 'Herramientas dev',
    heading: {
      family: 'Space Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['técnica', 'monoespaciada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Plus Jakarta Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['moderna', 'geométrica'],
      bestFor: 'body',
    },
    rationale: 'Herramientas para desarrolladores.',
    mood: ['técnico', 'moderno'],
    character: ['technical', 'bold'],
  },
  {
    id: 'display-space-mono-grotesk',
    displayName: 'Web3 creativo',
    heading: {
      family: 'Space Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['técnica', 'monoespaciada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Space Grotesk',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Grotesk',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'body',
    },
    rationale: 'Voz Web3.',
    mood: ['técnico', 'digital'],
    character: ['technical', 'geometric'],
  },
  {
    id: 'display-bebas-work',
    displayName: 'Deportes impacto',
    heading: {
      family: 'Bebas Neue',
      googleFontsRef: 'https://fonts.google.com/specimen/Bebas+Neue',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['condensada', 'impacto'],
      bestFor: 'heading',
    },
    body: {
      family: 'Work Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Work+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'versátil'],
      bestFor: 'body',
    },
    rationale: 'Deportes e impacto.',
    mood: ['enérgico', 'directo'],
    character: ['bold'],
  },
  {
    id: 'display-archivo-black-archivo',
    displayName: 'B2B fuerte',
    heading: {
      family: 'Archivo Black',
      googleFontsRef: 'https://fonts.google.com/specimen/Archivo+Black',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['fuerte', 'condensada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Archivo',
      googleFontsRef: 'https://fonts.google.com/specimen/Archivo',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['versátil', 'funcional'],
      bestFor: 'body',
    },
    rationale: 'B2B con presencia.',
    mood: ['enérgico', 'institucional'],
    character: ['bold', 'technical'],
  },
  {
    id: 'display-gravitas-poppins',
    displayName: 'Branding display',
    heading: {
      family: 'Gravitas One',
      googleFontsRef: 'https://fonts.google.com/specimen/Gravitas+One',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'contundente'],
      bestFor: 'heading',
    },
    body: {
      family: 'Poppins',
      googleFontsRef: 'https://fonts.google.com/specimen/Poppins',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'body',
    },
    rationale: 'Branding con display.',
    mood: ['expresivo', 'cálido'],
    character: ['bold', 'warm'],
  },
  {
    id: 'display-unbounded-inter',
    displayName: 'Creatividad',
    heading: {
      family: 'Unbounded',
      googleFontsRef: 'https://fonts.google.com/specimen/Unbounded',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['geométrica', 'expresiva'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Creatividad.',
    mood: ['expresivo', 'moderno'],
    character: ['bold', 'geometric'],
  },
  {
    id: 'display-syne-syne',
    displayName: 'Branding Syne',
    heading: {
      family: 'Syne',
      googleFontsRef: 'https://fonts.google.com/specimen/Syne',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Syne',
      googleFontsRef: 'https://fonts.google.com/specimen/Syne',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['expresiva', 'geométrica'],
      bestFor: 'body',
    },
    rationale: 'Branding con una sola voz Syne.',
    mood: ['expresivo', 'moderno'],
    character: ['bold', 'geometric'],
  },
  {
    id: 'display-league-spartan-inter',
    displayName: 'Marketing',
    heading: {
      family: 'League Spartan',
      googleFontsRef: 'https://fonts.google.com/specimen/League+Spartan',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['geométrica', 'contundente'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Marketing.',
    mood: ['enérgico', 'moderno'],
    character: ['bold'],
  },
  {
    id: 'display-oswald-inter',
    displayName: 'Noticias',
    heading: {
      family: 'Oswald',
      googleFontsRef: 'https://fonts.google.com/specimen/Oswald',
      classification: 'sans-serif',
      contrast: 'high',
      xHeight: 'high',
      personality: ['condensada', 'directa'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Noticias.',
    mood: ['directo', 'moderno'],
    character: ['bold', 'technical'],
  },
  {
    id: 'display-anton-inter',
    displayName: 'Impacto',
    heading: {
      family: 'Anton',
      googleFontsRef: 'https://fonts.google.com/specimen/Anton',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['condensada', 'impacto'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Impacto máximo.',
    mood: ['enérgico', 'directo'],
    character: ['bold'],
  },
  {
    id: 'display-archivo-narrow-inter',
    displayName: 'Dashboards densos',
    heading: {
      family: 'Archivo Narrow',
      googleFontsRef: 'https://fonts.google.com/specimen/Archivo+Narrow',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['condensada', 'técnica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Dashboards densos.',
    mood: ['técnico', 'preciso'],
    character: ['technical', 'compact'],
  },
  {
    id: 'display-bricolage-manrope',
    displayName: 'IA creativa',
    heading: {
      family: 'Bricolage Grotesque',
      googleFontsRef: 'https://fonts.google.com/specimen/Bricolage+Grotesque',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['amable', 'clara'],
      bestFor: 'body',
    },
    rationale: 'IA creativa.',
    mood: ['expresivo', 'moderno'],
    character: ['bold', 'warm'],
  },
];
