import type { FontPair } from '../fontPairTypes';

export const FRIENDLY_PAIRS: FontPair[] = [
  {
    id: 'friendly-caveat-karla',
    displayName: 'Onboarding cálido',
    heading: {
      family: 'Caveat',
      googleFontsRef: 'https://fonts.google.com/specimen/Caveat',
      classification: 'display',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['manuscrita', 'cálida'],
      bestFor: 'heading',
    },
    body: {
      family: 'Karla',
      googleFontsRef: 'https://fonts.google.com/specimen/Karla',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'simple'],
      bestFor: 'body',
    },
    rationale: 'Manuscrita cálida con Karla legible para onboarding.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'friendly-aboreto-gotu',
    displayName: 'Lifestyle',
    heading: {
      family: 'Aboreto',
      googleFontsRef: 'https://fonts.google.com/specimen/Aboreto',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'orgánica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Gotu',
      googleFontsRef: 'https://fonts.google.com/specimen/Gotu',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'amable'],
      bestFor: 'body',
    },
    rationale: 'Display Aboreto con Gotu para marcas lifestyle.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'friendly-sniglet-mplus',
    displayName: 'Niños',
    heading: {
      family: 'Sniglet',
      googleFontsRef: 'https://fonts.google.com/specimen/Sniglet',
      classification: 'display',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['juguetona', 'redondeada'],
      bestFor: 'heading',
    },
    body: {
      family: 'M PLUS Rounded 1c',
      googleFontsRef: 'https://fonts.google.com/specimen/M+PLUS+Rounded+1c',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['redondeada', 'amable'],
      bestFor: 'body',
    },
    rationale: 'Sniglet juguetón con M PLUS Rounded para audiencias infantiles.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'friendly-quicksand-nunito',
    displayName: 'Educación redonda',
    heading: {
      family: 'Quicksand',
      googleFontsRef: 'https://fonts.google.com/specimen/Quicksand',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['redondeada', 'amable'],
      bestFor: 'heading',
    },
    body: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'body',
    },
    rationale: 'Quicksand y Nunito redondeadas para educación.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'friendly-baloo-nunito',
    displayName: 'Apps infantiles',
    heading: {
      family: 'Baloo 2',
      googleFontsRef: 'https://fonts.google.com/specimen/Baloo+2',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['expresiva', 'redondeada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'body',
    },
    rationale: 'Baloo 2 expresivo con Nunito amable para apps infantiles.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'friendly-comfortaa-rubik',
    displayName: 'Casual',
    heading: {
      family: 'Comfortaa',
      googleFontsRef: 'https://fonts.google.com/specimen/Comfortaa',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['redondeada', 'relajada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Rubik',
      googleFontsRef: 'https://fonts.google.com/specimen/Rubik',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Comfortaa y Rubik redondeadas para productos casuales.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
];
