import type { FontPair } from '../pairings';

export const LEGACY_FONT_PAIRS: FontPair[] = [
  {
    id: 'editorial-lora-inter',
    displayName: 'Editorial clara',
    heading: {
      family: 'Lora',
      googleFontsRef: 'https://fonts.google.com/specimen/Lora',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'serena'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['legible', 'neutral'],
      bestFor: 'body',
    },
    rationale: 'Serif editorial con lectura digital compacta.',
    mood: ['editorial', 'sereno'],
    character: ['editorial'],
  },
  {
    id: 'luxury-playfair-source-serif',
    displayName: 'Lujo editorial',
    heading: {
      family: 'Playfair Display',
      googleFontsRef: 'https://fonts.google.com/specimen/Playfair+Display',
      classification: 'serif',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['elegante', 'clásica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Serif 4',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Serif+4',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'cálida'],
      bestFor: 'body',
    },
    rationale: 'Contraste refinado para marcas de alta intención visual.',
    mood: ['editorial', 'elegante'],
    character: ['editorial', 'elegante'],
  },
  {
    id: 'technical-ibm-plex',
    displayName: 'Técnico humano',
    heading: {
      family: 'IBM Plex Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['precisa', 'sobria'],
      bestFor: 'heading',
    },
    body: {
      family: 'IBM Plex Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['técnica', 'sistemática'],
      bestFor: 'body',
    },
    rationale: 'Sistema técnico con suficiente humanidad en titulares.',
    mood: ['técnico', 'preciso'],
    character: ['technical'],
  },
  {
    id: 'geometric-space-grotesk-work',
    displayName: 'Geométrico limpio',
    heading: {
      family: 'Space Grotesk',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Grotesk',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'heading',
    },
    body: {
      family: 'Work Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Work+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'versátil'],
      bestFor: 'body',
    },
    rationale: 'Geometría fuerte con cuerpo neutral para interfaces.',
    mood: ['geométrico', 'moderno'],
    character: ['geometric'],
  },
  {
    id: 'warm-fraunces-manrope',
    displayName: 'Cálido expresivo',
    heading: {
      family: 'Fraunces',
      googleFontsRef: 'https://fonts.google.com/specimen/Fraunces',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'orgánica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['amable', 'clara'],
      bestFor: 'body',
    },
    rationale: 'Titulares con carácter y cuerpo abierto para lectura cómoda.',
    mood: ['cálido', 'expresivo'],
    character: ['warm'],
  },
  {
    id: 'minimal-instrument-sans-newsreader',
    displayName: 'Minimal editorial',
    heading: {
      family: 'Newsreader',
      googleFontsRef: 'https://fonts.google.com/specimen/Newsreader',
      classification: 'serif',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['editorial', 'calmada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Instrument Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Instrument+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['minimal', 'funcional'],
      bestFor: 'body',
    },
    rationale: 'Lectura contemporánea con una voz editorial sobria.',
    mood: ['editorial', 'minimal'],
    character: ['editorial', 'minimal'],
  },
  {
    id: 'friendly-nunito-bitter',
    displayName: 'Amable confiable',
    heading: {
      family: 'Bitter',
      googleFontsRef: 'https://fonts.google.com/specimen/Bitter',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['confiable', 'cálida'],
      bestFor: 'heading',
    },
    body: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'body',
    },
    rationale: 'Tono accesible para productos educativos o comunitarios.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'startup-sora-public-sans',
    displayName: 'Producto moderno',
    heading: {
      family: 'Sora',
      googleFontsRef: 'https://fonts.google.com/specimen/Sora',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Public Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Public+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['institucional', 'clara'],
      bestFor: 'body',
    },
    rationale: 'Titulares con presencia y cuerpo robusto para producto.',
    mood: ['moderno', 'preciso'],
    character: ['technical', 'geometric'],
  },
  {
    id: 'bold-display-oswald-source-sans',
    displayName: 'Impacto directo',
    heading: {
      family: 'Oswald',
      googleFontsRef: 'https://fonts.google.com/specimen/Oswald',
      classification: 'sans-serif',
      contrast: 'high',
      xHeight: 'high',
      personality: ['condensada', 'directa'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Ideal para jerarquías fuertes sin sacrificar lectura.',
    mood: ['enérgico', 'directo'],
    character: ['bold'],
  },
  {
    id: 'crafted-cormorant-karla',
    displayName: 'Artesanal pulido',
    heading: {
      family: 'Cormorant Garamond',
      googleFontsRef: 'https://fonts.google.com/specimen/Cormorant+Garamond',
      classification: 'serif',
      contrast: 'high',
      xHeight: 'low',
      personality: ['artesanal', 'elegante'],
      bestFor: 'heading',
    },
    body: {
      family: 'Karla',
      googleFontsRef: 'https://fonts.google.com/specimen/Karla',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'simple'],
      bestFor: 'body',
    },
    rationale: 'Contraste boutique con lectura cotidiana.',
    mood: ['cálido', 'artesanal'],
    character: ['warm', 'crafted'],
  },
  {
    id: 'academic-crimson-pro-libre-franklin',
    displayName: 'Académico actual',
    heading: {
      family: 'Crimson Pro',
      googleFontsRef: 'https://fonts.google.com/specimen/Crimson+Pro',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['académica', 'clásica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Libre Franklin',
      googleFontsRef: 'https://fonts.google.com/specimen/Libre+Franklin',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['institucional', 'estable'],
      bestFor: 'body',
    },
    rationale: 'Seriedad editorial con tono de interfaz contemporánea.',
    mood: ['editorial', 'institucional'],
    character: ['editorial', 'formal'],
  },
  {
    id: 'tech-mono-jetbrains-inter',
    displayName: 'Dev técnico',
    heading: {
      family: 'JetBrains Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/JetBrains+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['técnica', 'precisa'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Código y producto en un sistema claro.',
    mood: ['técnico', 'preciso'],
    character: ['technical'],
  },
  {
    id: 'humanist-merriweather-open-sans',
    displayName: 'Humanista legible',
    heading: {
      family: 'Merriweather',
      googleFontsRef: 'https://fonts.google.com/specimen/Merriweather',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'confiable'],
      bestFor: 'heading',
    },
    body: {
      family: 'Open Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Open+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['accesible', 'neutral'],
      bestFor: 'body',
    },
    rationale: 'Par seguro para contenido largo y marcas de servicio.',
    mood: ['sereno', 'confiable'],
    character: ['warm', 'accessible'],
  },
  {
    id: 'elegant-prata-mulish',
    displayName: 'Elegancia simple',
    heading: {
      family: 'Prata',
      googleFontsRef: 'https://fonts.google.com/specimen/Prata',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['elegante', 'editorial'],
      bestFor: 'heading',
    },
    body: {
      family: 'Mulish',
      googleFontsRef: 'https://fonts.google.com/specimen/Mulish',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['suave', 'limpia'],
      bestFor: 'body',
    },
    rationale: 'Alto contraste sin perder claridad en UI.',
    mood: ['elegante', 'minimal'],
    character: ['editorial', 'elegant'],
  },
  {
    id: 'compact-barlow-roboto-slab',
    displayName: 'Compacto sólido',
    heading: {
      family: 'Roboto Slab',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto+Slab',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['sólida', 'estructurada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Barlow',
      googleFontsRef: 'https://fonts.google.com/specimen/Barlow',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['compacta', 'técnica'],
      bestFor: 'body',
    },
    rationale: 'Bloques densos con buena economía espacial.',
    mood: ['técnico', 'estructurado'],
    character: ['technical', 'compact'],
  },
  {
    id: 'creative-rubik-abril',
    displayName: 'Creativo fuerte',
    heading: {
      family: 'Abril Fatface',
      googleFontsRef: 'https://fonts.google.com/specimen/Abril+Fatface',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'audaz'],
      bestFor: 'heading',
    },
    body: {
      family: 'Rubik',
      googleFontsRef: 'https://fonts.google.com/specimen/Rubik',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Display memorable con cuerpo amable y rápido.',
    mood: ['expresivo', 'enérgico'],
    character: ['bold', 'warm'],
  },
  {
    id: 'calm-domine-lexend',
    displayName: 'Calma accesible',
    heading: {
      family: 'Domine',
      googleFontsRef: 'https://fonts.google.com/specimen/Domine',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['serena', 'legible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Lexend',
      googleFontsRef: 'https://fonts.google.com/specimen/Lexend',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['accesible', 'abierta'],
      bestFor: 'body',
    },
    rationale: 'Lectura calmada para marcas educativas o de bienestar.',
    mood: ['sereno', 'cálido'],
    character: ['warm', 'accessible'],
  },
  {
    id: 'structured-archivo-pt-serif',
    displayName: 'Estructura editorial',
    heading: {
      family: 'Archivo',
      googleFontsRef: 'https://fonts.google.com/specimen/Archivo',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['firme', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'PT Serif',
      googleFontsRef: 'https://fonts.google.com/specimen/PT+Serif',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'estable'],
      bestFor: 'body',
    },
    rationale: 'Jerarquía de interfaz con lectura editorial.',
    mood: ['geométrico', 'editorial'],
    character: ['geometric', 'editorial'],
  },
  {
    id: 'fresh-outfit-noto-serif',
    displayName: 'Fresco editorial',
    heading: {
      family: 'Outfit',
      googleFontsRef: 'https://fonts.google.com/specimen/Outfit',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'fresca'],
      bestFor: 'heading',
    },
    body: {
      family: 'Noto Serif',
      googleFontsRef: 'https://fonts.google.com/specimen/Noto+Serif',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['global', 'editorial'],
      bestFor: 'body',
    },
    rationale: 'Titular limpio con cuerpo serif de lectura amplia.',
    mood: ['moderno', 'editorial'],
    character: ['geometric', 'editorial'],
  },
  {
    id: 'neutral-dm-sans-eb-garamond',
    displayName: 'Neutral con voz',
    heading: {
      family: 'EB Garamond',
      googleFontsRef: 'https://fonts.google.com/specimen/EB+Garamond',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['clásica', 'editorial'],
      bestFor: 'heading',
    },
    body: {
      family: 'DM Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/DM+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Una voz clásica apoyada por lectura digital neutra.',
    mood: ['editorial', 'neutral'],
    character: ['editorial', 'minimal'],
  },
];
