import type { FontPair } from '../fontPairTypes';

export const MONO_SANS_PAIRS: FontPair[] = [
  {
    id: 'mono-roboto-roboto',
    displayName: 'Código Roboto',
    heading: {
      family: 'Roboto Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['técnica', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Roboto',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'funcional'],
      bestFor: 'body',
    },
    rationale: 'Monospace Roboto con cuerpo funcional para interfaces de código.',
    mood: ['técnico', 'preciso'],
    character: ['technical'],
  },
  {
    id: 'mono-space-inter',
    displayName: 'Developer',
    heading: {
      family: 'Space Mono',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Mono',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['técnica', 'monoespaciada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Space Mono e Inter para herramientas de desarrollo.',
    mood: ['técnico', 'preciso'],
    character: ['technical'],
  },
  {
    id: 'mono-firacode-inter',
    displayName: 'Dev tools',
    heading: {
      family: 'Fira Code',
      googleFontsRef: 'https://fonts.google.com/specimen/Fira+Code',
      classification: 'monospace',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['técnica', 'ligaduras'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Fira Code con Inter para IDEs y documentación técnica.',
    mood: ['técnico', 'preciso'],
    character: ['technical'],
  },
];
