import type { FontPair } from '../fontPairTypes';

export const SANS_SERIF_PAIRS: FontPair[] = [
  {
    id: 'serif-playfair-lato',
    displayName: 'Editorial moda',
    heading: {
      family: 'Playfair Display',
      googleFontsRef: 'https://fonts.google.com/specimen/Playfair+Display',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['elegante', 'clásica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Lato',
      googleFontsRef: 'https://fonts.google.com/specimen/Lato',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Editorial para moda.',
    mood: ['editorial', 'elegante'],
    character: ['editorial', 'elegant'],
  },
  {
    id: 'serif-raleway-merriweather',
    displayName: 'Elegante blogs',
    heading: {
      family: 'Raleway',
      googleFontsRef: 'https://fonts.google.com/specimen/Raleway',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'limpia'],
      bestFor: 'heading',
    },
    body: {
      family: 'Merriweather',
      googleFontsRef: 'https://fonts.google.com/specimen/Merriweather',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'confiable'],
      bestFor: 'body',
    },
    rationale: 'Elegante para blogs.',
    mood: ['editorial', 'elegante'],
    character: ['editorial', 'elegant'],
  },
  {
    id: 'serif-montserrat-lora',
    displayName: 'Clásico moderno',
    heading: {
      family: 'Montserrat',
      googleFontsRef: 'https://fonts.google.com/specimen/Montserrat',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'firme'],
      bestFor: 'heading',
    },
    body: {
      family: 'Lora',
      googleFontsRef: 'https://fonts.google.com/specimen/Lora',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'serena'],
      bestFor: 'body',
    },
    rationale: 'Clásico moderno para contenido.',
    mood: ['editorial', 'moderno'],
    character: ['editorial', 'geometric'],
  },
  {
    id: 'serif-roboto-lora',
    displayName: 'UI y lectura',
    heading: {
      family: 'Roboto',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Lora',
      googleFontsRef: 'https://fonts.google.com/specimen/Lora',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'serena'],
      bestFor: 'body',
    },
    rationale: 'UI + lectura para noticias.',
    mood: ['editorial', 'confiable'],
    character: ['editorial', 'technical'],
  },
  {
    id: 'serif-source-alegreya',
    displayName: 'Docs artículos',
    heading: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Alegreya',
      googleFontsRef: 'https://fonts.google.com/specimen/Alegreya',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'cálida'],
      bestFor: 'body',
    },
    rationale: 'Documentación y artículos.',
    mood: ['editorial', 'institucional'],
    character: ['editorial'],
  },
  {
    id: 'serif-dm-serif-dm-sans',
    displayName: 'Editorial revistas',
    heading: {
      family: 'DM Serif Display',
      googleFontsRef: 'https://fonts.google.com/specimen/DM+Serif+Display',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['elegante', 'editorial'],
      bestFor: 'heading',
    },
    body: {
      family: 'DM Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/DM+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Editorial para revistas.',
    mood: ['editorial', 'elegante'],
    character: ['editorial', 'elegant'],
  },
  {
    id: 'serif-fraunces-inter',
    displayName: 'Moderno branding',
    heading: {
      family: 'Fraunces',
      googleFontsRef: 'https://fonts.google.com/specimen/Fraunces',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'orgánica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Moderno para branding.',
    mood: ['cálido', 'editorial'],
    character: ['editorial', 'warm'],
  },
  {
    id: 'serif-libre-baskerville-source',
    displayName: 'Tradicional lectura',
    heading: {
      family: 'Libre Baskerville',
      googleFontsRef: 'https://fonts.google.com/specimen/Libre+Baskerville',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['clásica', 'editorial'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Tradicional para lectura.',
    mood: ['editorial', 'confiable'],
    character: ['editorial'],
  },
  {
    id: 'serif-cormorant-proza',
    displayName: 'Lujo premium',
    heading: {
      family: 'Cormorant Garamond',
      googleFontsRef: 'https://fonts.google.com/specimen/Cormorant+Garamond',
      classification: 'serif',
      contrast: 'high',
      xHeight: 'low',
      personality: ['artesanal', 'elegante'],
      bestFor: 'heading',
    },
    body: {
      family: 'Proza Libre',
      googleFontsRef: 'https://fonts.google.com/specimen/Proza+Libre',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Lujo para marcas premium.',
    mood: ['elegante', 'editorial'],
    character: ['editorial', 'elegant'],
  },
  {
    id: 'serif-ibm-plex',
    displayName: 'Enterprise B2B',
    heading: {
      family: 'IBM Plex Serif',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Serif',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['precisa', 'institucional'],
      bestFor: 'heading',
    },
    body: {
      family: 'IBM Plex Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['precisa', 'sobria'],
      bestFor: 'body',
    },
    rationale: 'Enterprise B2B.',
    mood: ['institucional', 'preciso'],
    character: ['editorial', 'technical'],
  },
  {
    id: 'serif-noto-pair',
    displayName: 'Global multilenguaje',
    heading: {
      family: 'Noto Serif',
      googleFontsRef: 'https://fonts.google.com/specimen/Noto+Serif',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['global', 'editorial'],
      bestFor: 'heading',
    },
    body: {
      family: 'Noto Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Noto+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['global', 'neutral'],
      bestFor: 'body',
    },
    rationale: 'Global multilenguaje.',
    mood: ['editorial', 'confiable'],
    character: ['editorial', 'accessible'],
  },
  {
    id: 'serif-zilla-lexend',
    displayName: 'Accesible educación',
    heading: {
      family: 'Zilla Slab',
      googleFontsRef: 'https://fonts.google.com/specimen/Zilla+Slab',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['accesible', 'cálida'],
      bestFor: 'heading',
    },
    body: {
      family: 'Lexend',
      googleFontsRef: 'https://fonts.google.com/specimen/Lexend',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['accesible', 'abierta'],
      bestFor: 'body',
    },
    rationale: 'Accesible para educación.',
    mood: ['cálido', 'accesible'],
    character: ['accessible', 'warm'],
  },
  {
    id: 'serif-spectral-inter',
    displayName: 'Editorial blogs',
    heading: {
      family: 'Spectral',
      googleFontsRef: 'https://fonts.google.com/specimen/Spectral',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'calmada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Editorial para blogs modernos.',
    mood: ['editorial', 'sereno'],
    character: ['editorial', 'minimal'],
  },
  {
    id: 'serif-newsreader-inter',
    displayName: 'Revistas contenido',
    heading: {
      family: 'Newsreader',
      googleFontsRef: 'https://fonts.google.com/specimen/Newsreader',
      classification: 'serif',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['editorial', 'calmada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Revistas y contenido.',
    mood: ['editorial', 'moderno'],
    character: ['editorial'],
  },
  {
    id: 'serif-bitter-source',
    displayName: 'Docs técnicos',
    heading: {
      family: 'Bitter',
      googleFontsRef: 'https://fonts.google.com/specimen/Bitter',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['confiable', 'cálida'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Documentación y blogs técnicos.',
    mood: ['editorial', 'preciso'],
    character: ['editorial', 'technical'],
  },
  {
    id: 'serif-literata-inter',
    displayName: 'Lectura educativa',
    heading: {
      family: 'Literata',
      googleFontsRef: 'https://fonts.google.com/specimen/Literata',
      classification: 'serif',
      contrast: 'medium',
      xHeight: 'medium',
      personality: ['editorial', 'accesible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Lectura para apps educativas.',
    mood: ['editorial', 'cálido'],
    character: ['editorial', 'accessible'],
  },
];
