import type { FontPair } from '../pairings';

export const SANS_SANS_PAIRS: FontPair[] = [
  {
    id: 'sans-inter-krub',
    displayName: 'Tech limpio',
    heading: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Krub',
      googleFontsRef: 'https://fonts.google.com/specimen/Krub',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Sans limpia para SaaS y dashboards.',
    mood: ['técnico', 'moderno'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'sans-montserrat-karla',
    displayName: 'Geométrico humanista',
    heading: {
      family: 'Montserrat',
      googleFontsRef: 'https://fonts.google.com/specimen/Montserrat',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'firme'],
      bestFor: 'heading',
    },
    body: {
      family: 'Karla',
      googleFontsRef: 'https://fonts.google.com/specimen/Karla',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'simple'],
      bestFor: 'body',
    },
    rationale: 'Geometría suave con cuerpo humanista.',
    mood: ['geométrico', 'confiable'],
    character: ['geometric', 'warm'],
  },
  {
    id: 'sans-poppins-open-sans',
    displayName: 'Moderno web',
    heading: {
      family: 'Poppins',
      googleFontsRef: 'https://fonts.google.com/specimen/Poppins',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'heading',
    },
    body: {
      family: 'Open Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Open+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['accesible', 'neutral'],
      bestFor: 'body',
    },
    rationale: 'Par versátil para web apps.',
    mood: ['moderno', 'digital'],
    character: ['geometric', 'minimal'],
  },
  {
    id: 'sans-roboto-nunito',
    displayName: 'Neutro amigable',
    heading: {
      family: 'Roboto',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'body',
    },
    rationale: 'Neutro Android/móvil con cuerpo amable.',
    mood: ['cálido', 'confiable'],
    character: ['warm', 'technical'],
  },
  {
    id: 'sans-work-source',
    displayName: 'Profesional digital',
    heading: {
      family: 'Work Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Work+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'versátil'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Profesional para productos digitales.',
    mood: ['preciso', 'profesional'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'sans-manrope-inter',
    displayName: 'Premium producto',
    heading: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['moderna', 'precisa'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Premium para fintech y productividad.',
    mood: ['moderno', 'preciso'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'sans-space-grotesk-inter',
    displayName: 'Tech moderno',
    heading: {
      family: 'Space Grotesk',
      googleFontsRef: 'https://fonts.google.com/specimen/Space+Grotesk',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Tech moderno para IA, Web3 y startups.',
    mood: ['técnico', 'moderno'],
    character: ['technical', 'geometric'],
  },
  {
    id: 'sans-syne-inter',
    displayName: 'Branding fuerte',
    heading: {
      family: 'Syne',
      googleFontsRef: 'https://fonts.google.com/specimen/Syne',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Titulares con voz de marca fuerte.',
    mood: ['expresivo', 'moderno'],
    character: ['bold', 'geometric'],
  },
  {
    id: 'sans-prompt-rubik',
    displayName: 'Redondeado EdTech',
    heading: {
      family: 'Prompt',
      googleFontsRef: 'https://fonts.google.com/specimen/Prompt',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Rubik',
      googleFontsRef: 'https://fonts.google.com/specimen/Rubik',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Redondeado amable para educación.',
    mood: ['cálido', 'amable'],
    character: ['warm'],
  },
  {
    id: 'sans-albert-barlow',
    displayName: 'Minimalista SaaS',
    heading: {
      family: 'Albert Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Albert+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['minimal', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Barlow',
      googleFontsRef: 'https://fonts.google.com/specimen/Barlow',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['compacta', 'técnica'],
      bestFor: 'body',
    },
    rationale: 'Minimalista para SaaS y portfolios.',
    mood: ['minimal', 'preciso'],
    character: ['minimal', 'technical'],
  },
  {
    id: 'sans-reddit-sora',
    displayName: 'Contemporáneo social',
    heading: {
      family: 'Reddit Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Reddit+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Sora',
      googleFontsRef: 'https://fonts.google.com/specimen/Sora',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'body',
    },
    rationale: 'Contemporáneo para apps sociales.',
    mood: ['moderno', 'digital'],
    character: ['geometric', 'technical'],
  },
  {
    id: 'sans-urbanist-redhat',
    displayName: 'Elegante fintech',
    heading: {
      family: 'Urbanist',
      googleFontsRef: 'https://fonts.google.com/specimen/Urbanist',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Red Hat Display',
      googleFontsRef: 'https://fonts.google.com/specimen/Red+Hat+Display',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'moderna'],
      bestFor: 'body',
    },
    rationale: 'Elegante para fintech.',
    mood: ['elegante', 'moderno'],
    character: ['elegant', 'minimal'],
  },
  {
    id: 'sans-mulish-karla',
    displayName: 'Calmado wellness',
    heading: {
      family: 'Mulish',
      googleFontsRef: 'https://fonts.google.com/specimen/Mulish',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['suave', 'limpia'],
      bestFor: 'heading',
    },
    body: {
      family: 'Karla',
      googleFontsRef: 'https://fonts.google.com/specimen/Karla',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['humana', 'simple'],
      bestFor: 'body',
    },
    rationale: 'Calmado para wellness.',
    mood: ['sereno', 'cálido'],
    character: ['warm', 'minimal'],
  },
  {
    id: 'sans-bricolage-inter',
    displayName: 'Creativo IA',
    heading: {
      family: 'Bricolage Grotesque',
      googleFontsRef: 'https://fonts.google.com/specimen/Bricolage+Grotesque',
      classification: 'display',
      contrast: 'high',
      xHeight: 'medium',
      personality: ['expresiva', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Creativo para productos de IA.',
    mood: ['expresivo', 'técnico'],
    character: ['bold', 'technical'],
  },
  {
    id: 'sans-outfit-inter',
    displayName: 'Limpio moderno',
    heading: {
      family: 'Outfit',
      googleFontsRef: 'https://fonts.google.com/specimen/Outfit',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'fresca'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Limpio para apps modernas.',
    mood: ['moderno', 'limpio'],
    character: ['geometric', 'minimal'],
  },
  {
    id: 'sans-outfit-manrope',
    displayName: 'Elegante SaaS',
    heading: {
      family: 'Outfit',
      googleFontsRef: 'https://fonts.google.com/specimen/Outfit',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'elegante'],
      bestFor: 'heading',
    },
    body: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['amable', 'clara'],
      bestFor: 'body',
    },
    rationale: 'Elegante para SaaS.',
    mood: ['elegante', 'moderno'],
    character: ['geometric', 'elegant'],
  },
  {
    id: 'sans-sora-inter',
    displayName: 'Tecnología AI',
    heading: {
      family: 'Sora',
      googleFontsRef: 'https://fonts.google.com/specimen/Sora',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Tecnología para productos de AI.',
    mood: ['técnico', 'moderno'],
    character: ['technical', 'geometric'],
  },
];
