import type { FontPair } from '../fontPairTypes';

export const SINGLE_FAMILY_PAIRS: FontPair[] = [
  {
    id: 'family-inter',
    displayName: 'Familia Inter',
    heading: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Inter',
      googleFontsRef: 'https://fonts.google.com/specimen/Inter',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['minimal', 'technical'],
  },
  {
    id: 'family-manrope',
    displayName: 'Familia Manrope',
    heading: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['moderna', 'precisa'],
      bestFor: 'heading',
    },
    body: {
      family: 'Manrope',
      googleFontsRef: 'https://fonts.google.com/specimen/Manrope',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['moderna', 'precisa'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['minimal', 'technical'],
  },
  {
    id: 'family-plus-jakarta',
    displayName: 'Familia Plus Jakarta',
    heading: {
      family: 'Plus Jakarta Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'heading',
    },
    body: {
      family: 'Plus Jakarta Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'moderna'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['geometric', 'minimal'],
  },
  {
    id: 'family-ibm-plex-sans',
    displayName: 'Familia IBM Plex Sans',
    heading: {
      family: 'IBM Plex Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['precisa', 'sobria'],
      bestFor: 'heading',
    },
    body: {
      family: 'IBM Plex Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/IBM+Plex+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['precisa', 'sobria'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['técnico', 'moderno'],
    character: ['technical'],
  },
  {
    id: 'family-source-sans',
    displayName: 'Familia Source Sans 3',
    heading: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'heading',
    },
    body: {
      family: 'Source Sans 3',
      googleFontsRef: 'https://fonts.google.com/specimen/Source+Sans+3',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['funcional', 'legible'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'family-work-sans',
    displayName: 'Familia Work Sans',
    heading: {
      family: 'Work Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Work+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'versátil'],
      bestFor: 'heading',
    },
    body: {
      family: 'Work Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Work+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['limpia', 'versátil'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'family-sora',
    displayName: 'Familia Sora',
    heading: {
      family: 'Sora',
      googleFontsRef: 'https://fonts.google.com/specimen/Sora',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Sora',
      googleFontsRef: 'https://fonts.google.com/specimen/Sora',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['digital', 'geométrica'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['geometric', 'technical'],
  },
  {
    id: 'family-outfit',
    displayName: 'Familia Outfit',
    heading: {
      family: 'Outfit',
      googleFontsRef: 'https://fonts.google.com/specimen/Outfit',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'fresca'],
      bestFor: 'heading',
    },
    body: {
      family: 'Outfit',
      googleFontsRef: 'https://fonts.google.com/specimen/Outfit',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['geométrica', 'fresca'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['geometric', 'minimal'],
  },
  {
    id: 'family-instrument-sans',
    displayName: 'Familia Instrument Sans',
    heading: {
      family: 'Instrument Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Instrument+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['minimal', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Instrument Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Instrument+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['minimal', 'funcional'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['minimal', 'technical'],
  },
  {
    id: 'family-urbanist',
    displayName: 'Familia Urbanist',
    heading: {
      family: 'Urbanist',
      googleFontsRef: 'https://fonts.google.com/specimen/Urbanist',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'geométrica'],
      bestFor: 'heading',
    },
    body: {
      family: 'Urbanist',
      googleFontsRef: 'https://fonts.google.com/specimen/Urbanist',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'geométrica'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['elegante', 'moderno'],
    character: ['elegant', 'minimal'],
  },
  {
    id: 'family-redhat-display',
    displayName: 'Familia Red Hat Display',
    heading: {
      family: 'Red Hat Display',
      googleFontsRef: 'https://fonts.google.com/specimen/Red+Hat+Display',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'moderna'],
      bestFor: 'heading',
    },
    body: {
      family: 'Red Hat Display',
      googleFontsRef: 'https://fonts.google.com/specimen/Red+Hat+Display',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['elegante', 'moderna'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['elegante', 'moderno'],
    character: ['elegant', 'technical'],
  },
  {
    id: 'family-rubik',
    displayName: 'Familia Rubik',
    heading: {
      family: 'Rubik',
      googleFontsRef: 'https://fonts.google.com/specimen/Rubik',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'digital'],
      bestFor: 'heading',
    },
    body: {
      family: 'Rubik',
      googleFontsRef: 'https://fonts.google.com/specimen/Rubik',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['redondeada', 'digital'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'cálido'],
    character: ['warm', 'geometric'],
  },
  {
    id: 'family-nunito',
    displayName: 'Familia Nunito',
    heading: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'heading',
    },
    body: {
      family: 'Nunito',
      googleFontsRef: 'https://fonts.google.com/specimen/Nunito',
      classification: 'sans-serif',
      contrast: 'low',
      xHeight: 'high',
      personality: ['amable', 'redondeada'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'cálido'],
    character: ['warm'],
  },
  {
    id: 'family-mulish',
    displayName: 'Familia Mulish',
    heading: {
      family: 'Mulish',
      googleFontsRef: 'https://fonts.google.com/specimen/Mulish',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['suave', 'limpia'],
      bestFor: 'heading',
    },
    body: {
      family: 'Mulish',
      googleFontsRef: 'https://fonts.google.com/specimen/Mulish',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['suave', 'limpia'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['warm', 'minimal'],
  },
  {
    id: 'family-roboto',
    displayName: 'Familia Roboto',
    heading: {
      family: 'Roboto',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'funcional'],
      bestFor: 'heading',
    },
    body: {
      family: 'Roboto',
      googleFontsRef: 'https://fonts.google.com/specimen/Roboto',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['neutral', 'funcional'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'limpio'],
    character: ['technical', 'minimal'],
  },
  {
    id: 'family-open-sans',
    displayName: 'Familia Open Sans',
    heading: {
      family: 'Open Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Open+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['accesible', 'neutral'],
      bestFor: 'heading',
    },
    body: {
      family: 'Open Sans',
      googleFontsRef: 'https://fonts.google.com/specimen/Open+Sans',
      classification: 'sans-serif',
      contrast: 'medium',
      xHeight: 'high',
      personality: ['accesible', 'neutral'],
      bestFor: 'body',
    },
    rationale: 'Una sola familia versátil para producto digital.',
    mood: ['moderno', 'cálido'],
    character: ['warm', 'accessible'],
  },
];
